export const GET_LIST_ACTORS = 'get list actors'
export const ADD_ACTORS = 'add actor'
export const UPDATE_ACTORS = 'update actor'
export const DELETE_ACTORS = 'delete actor'
export const EDIT_ACTOR = 'edit actor'